version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo docker permissions
      - chmod +x setup_docker_socket.sh  # Make the script executable
      - ./setup_docker_socket.sh  # Execute the script to set Docker socket permissions
      - docker login -u davtyan111 -p dckr_pat_mWhY4vnUhVD0S5Jyn_1SBrAgOG4
  build:
    commands:
      - echo Building Docker image...
      - docker build -t aws:v1 .
      - docker tag aws:v1 davtyan111/aws:v1
  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push davtyan111/aws:v1
      - echo Logging out from Docker Hub...
