version: 0.2

phases:
  pre_build:
    commands:
      # Check if Docker is installed
      - which docker
      - docker --version

      # Install Docker (if not already installed)
      - |
        if [ $? -ne 0 ]; then
          echo "Docker is not installed. Installing Docker..."
          curl -fsSL https://get.docker.com/ | sh
        fi

      # Authenticate with Docker Hub (replace with your Docker Hub credentials)
      - docker login -u davtyan111 -p dckr_pat_mWhY4vnUhVD0S5Jyn_1SBrAgOG4

  build:
    commands:
      # Build your Docker image (replace "your_docker_image" with your actual image name and tag)
      - docker build -t davtyan111/template_2 .

  post_build:
    commands:
      # Tag your Docker image (replace "your_docker_image" with your actual image name and tag)
      - docker tag davtyan111/template_2:latest davtyan111/davtyan111/template_2:latest

      # Push the Docker image to Docker Hub (replace "davtyan111" with your Docker Hub username)
      - docker push davtyan111/davtyan111/template_2:latest
