version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws configure set aws_access_key_id $access_key_id
      - aws configure set aws_secret_access_key $secret_access_key
      - echo "Running Docker-in-Docker"
      - docker run --privileged -d --name dind-container docker:dind
      - docker exec dind-container docker login --username AWS --password-stdin 068165388964.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker exec dind-container docker build -t test .
      - docker exec dind-container docker tag test 068165388964.dkr.ecr.us-east-2.amazonaws.com/test:latest

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker exec dind-container docker push 068165388964.dkr.ecr.us-east-2.amazonaws.com/test:latest
      - echo Logging out from Amazon ECR...
      - docker exec dind-container docker logout 068165388964.dkr.ecr.us-east-2.amazonaws.com
      - echo Give permission
      - chmod +x update.sh
      - echo Start update.sh
      - ./update.sh
      - echo Stopping Docker-in-Docker
      - docker stop dind-container
