version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_TOKEN" | docker login -u "davtyan111" --password-stdin
  build:
    commands:
      - echo Building Docker image...
      - docker build -t davtyan111/my-docker-image:latest .
  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push davtyan111/my-docker-image:latest
      - echo Logging out from Docker Hub...
      - docker logout

artifacts:
  files:
    - '**/*'
