version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - docker login -u $docker_hub_username -p $docker_hub_token
  build:
    commands:
      - echo Building Docker image...
      - docker build -t docker_image:v3 .
      - docker tag docker_image:v3 $docker_hub_username/docker_image:v3
  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push $docker_hub_username/docker_image:v3
      - echo Logging out from Docker Hub...
