version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_TOKEN" | docker login -u "davtyan111" --password-stdin
  build:
    commands:
      - echo Building Docker image...
      - docker build -t davtyan111/aws:latest .
  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push davtyan111/aws:latest
  finally:
    commands:
      - echo Logging out from Docker Hub...
      - docker logout
