version: 0.2

env:
  variables:
    DOCKERHUB_TOKEN: dckr_pat_mWhY4vnUhVD0S5Jyn_1SBrAgOG4

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - docker login --username davtyan111 --password $DOCKERHUB_TOKEN
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t davtyan111/aws:latest . 
      - docker push davtyan111/aws:latest
