version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo $DOCKERHUB_PASSWORD | docker login --username $davtyan111 --password-stdin
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $DOCKERHUB_USERNAME/my-image:latest .
      - docker push $DOCKERHUB_USERNAME/my-image:latest
