apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: laravel
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: aws
          image: 068165388964.dkr.ecr.us-east-2.amazonaws.com/test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
        #     - name: laravel-config
        #       mountPath: /aws/laravel      
        # - name: nginx
        #   image: nginx 
        #   ports:
        #     - containerPort: 80
        #   volumeMounts:
        #     - name: nginx-config
        #       mountPath: /etc/nginx/conf.d
        - name: laravel-app
          image: bitnami/laravel
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: laravel-config
              mountPath: /bitnami/laravel
          envFrom:
            - configMapRef:
                name: laravel-configmap
      volumes:
        - name: laravel-config
          configMap:
            name: laravel-configmap
        # - name: nginx-config
        #   configMap:
        #     name: nginx-configmap
